spring.application.name=gerenciador-documentos
spring.profiles.active=dev

# JPA comum
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Actuator — expõe o endpoint de health para os probes do Kubernetes
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
